const fs=require('fs')
const b=fs.readFileSync('scripts/openclaw-bridge/server.mjs','utf8')
console.log(b.split(/\n/).slice(300,400).join('\n'))
console.log('==== plugin routes ====')
const p=fs.readFileSync('integrations/openclaw/liangce-ingress/index.js','utf8')
for (const m of p.matchAll(/path:\s*['"][^'"]+/g)) console.log(m[0])
for (const m of p.matchAll(/['"]\/liangce[^'"]*/g)) console.log(m[0])
console.log('==== handoff api ====')
console.log(fs.readFileSync('simple-mind-map/bin/openclawHandoffApi.js','utf8'))
console.log('==== collab wire ====')
const c=fs.readFileSync('simple-mind-map/bin/collabServer.js','utf8')
c.split(/\n/).forEach((l,i)=>{if(/openclawHandoff|handoff/.test(l)) console.log((i+1)+':'+l.trim())})
